# Exercises 

I hope you learned the basics of Numpy. Now it's time to practice.

#### Import NumPy 

In [2]:
import numpy as np

#### Create an array of 10 zeros 

```python
Output: 
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

```python
output: 
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
```

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 Threes
Hint: Ones mathod with array operation

```python
Output: 
array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
```

In [5]:
np.ones(10)*3

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

#### Create an array of the integers from 20 to 40

```python
Output:
array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])
```

In [6]:
np.arange(20,41)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

#### Create an array of all the even integers from 20 to 40

```python
Output: 
array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])
```

In [7]:
np.arange(20,41,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

#### Create a 3x3 matrix

```python
Output:
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Generate a random number between 0 and 1

In [10]:
np.random.rand()

0.6910919593277065

#### Generate an array of 20 random numbers

In [11]:
np.random.rand(20)

array([0.21459888, 0.84825981, 0.91482484, 0.70371731, 0.79688988,
       0.6255737 , 0.05579357, 0.5060098 , 0.02646257, 0.81788143,
       0.77364874, 0.201407  , 0.68456661, 0.93151469, 0.06208582,
       0.75730535, 0.35907294, 0.18664525, 0.05863426, 0.19862103])

#### Create the following matrix:

In [13]:
np.linspace(.01, 1, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# Given the Below Matrix, find the answer to the following questions:

In [14]:
mat = np.arange(25,50).reshape(5,5)
mat

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

#### Get this slice

```python 
Output:
array([[31, 32, 33, 34],
       [36, 37, 38, 39],
       [41, 42, 43, 44]])
```

In [15]:
mat[1:4, 1:]

array([[31, 32, 33, 34],
       [36, 37, 38, 39],
       [41, 42, 43, 44]])

```python
Output:
array([[27],
       [32],
       [37],
       [42],
       [47]])
```

In [16]:
mat[:, 2:3]

array([[27],
       [32],
       [37],
       [42],
       [47]])

```python 
Output:
array([41, 42, 43])
```

In [17]:
mat[3][1:4]

array([41, 42, 43])

```python
Output:
array([[32, 33],
       [37, 38]])
```

In [18]:
mat[1:3, 2:4]

array([[32, 33],
       [37, 38]])

### Now do the following

#### Get the sum of all the values in mat

In [19]:
np.sum(mat)

np.int64(925)

#### Get the standard deviation of mat

In [20]:
np.std(mat)

np.float64(7.211102550927978)

#### Get the sum of all the columns in mat

In [21]:
np.sum(mat, axis=0)

array([175, 180, 185, 190, 195])

# Happy Practice!