Bois! We are going Deep DEep DEEp DEEEEEP inside `ML`. And we will face some roadblocks. First one is `numpy`.

This is a entry point and the first `boss` fight of this series. Because almost everything after this point is written in `numpy` or uses `numpy` functions. So, understanding and having a good knowledge of `numpy` is very important. So, without further ado, let's defeat `numpy`.

- [LinkedIn](https://www.linkedin.com/in/pro-programmer/)
- [YouTube](http://www.youtube.com/@itvaya)
- [gtihub](https://github.com/RishatTalukder/Machine-Learning-Zero-to-Hero)
- [Gmail](talukderrishat2@gmail.com)
- [discord](https://discord.gg/ZB495XggcF)

# Installation

You need `conda` installed in you system. If you don't have it, you can install it from [here](https://www.anaconda.com/products/distribution).

If you have `conda` installed, Just run the following command in your terminal:

```bash
conda install numpy
```

And 

If you don't have `conda` installed, you can still intall `numpy` on base `python` by running the following command:

```bash
pip install numpy
```

> I heavily recommend you to use `conda` for installing `numpy` because it will install all the dependencies of `numpy` and you will have less errors as our python package ecosystem grows.

# Intro

`Numpy` is faster `python`.

That's it end the article here. If you know `python` you already know 80% of `numpy`. 

Numpy specializes in `numerical computing`, specifically `arrays`.

> If you take python and optimise it so hard that it becomes faster than C++, you can call it `numpy`.

We can do everything we can do in `python` with `numpy` but it's waaaay faster than `python`.

But the main use case of `numpy` is `array/vector/matrix` operations. And that's what we will be doing in this article.

Let's take an array.

In [2]:
arr = [1,2,3,4,5]
arr

[1, 2, 3, 4, 5]

Here you can see a very simple python list. Which is pretty powerful on its own. But with numpy it becomes a superpower.

We can transform any array into a numpy array by using the `array()` function from numpy. We have to import `numpy` first because it's a external library.

In [3]:
import numpy as np

narr = np.array([1,2,3,4,5])
narr

array([1, 2, 3, 4, 5])

> In python you can rename a library when imported by using the `as` keyword. For example, if you import `numpy` as `np` you can use it as `np.array()` instead of `numpy.array()`.

Here you can see that by using the `np.array()` we are transforming our simple python list into a numpy array.

We can do the same thing with a 2D list as well.

In [4]:
arr_2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
narr_2D = np.array(arr_2D)
narr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

A numpy array gives us a lot of methods and attributes to work with the data. 

> A vector is a one-dimensional array which is a traditional array of numbers.
> A matrix is a two-dimensional array.

# Numpy Methods

There are a lot of methods that we can use to make and work with numpy arrays. 

First we can talk about the `arange` method. 

## Numpy Arange

This is equivalent to the python `range` function. Works exactly the same way.

In the range function, we can specify the start, stop, and step values.

And it generates a sequence of numbers from start to stop by step.

This is exactly what the `arange` method does. It also takes the start, stop, and step values and generates a sequence of numbers from start to stop by step.

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Just like for the range function, the start value in inclusive and the end value is exclusive. It's the same for `arange`.
> By default the starting index is set to 0 and the steps are 1.

In [6]:
np.arange(35, 45, 2)

array([35, 37, 39, 41, 43])

# Some Quick Numpy Array generators

If you want a array of all zeros, you can use the `zeros` function:

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

This will generate a numpy array of 5 zeros. We can also make a `matrix(2D)` array by specifying the number of `rows and columns` in a `tuple`.

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

And it'll generate a `3x4` matrix. The cool part is we can make 3D or more than 4D array of all zeros with this.

In [9]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [10]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

Numpy has another function that can generate arrays filled with only `one's`. This function is called `ones`. 

In [11]:
print('Array of 4 ones')
a = np.ones(4)
print(a)

print('2D array of all ones')
b = np.ones((2,2))
print(b)

print('3D array of all ones')
c = np.ones((2,2,2))
print(c)

Array of 4 ones
[1. 1. 1. 1.]
2D array of all ones
[[1. 1.]
 [1. 1.]]
3D array of all ones
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


This method works exactly same the `zeros` method, but it generates array of any dimentions with all elements as `Ones`.

Now, another very useful method I want to talk about is `linspace` method. This method is used to generate array with evenly spaced elements.

Let me break it down with an example.

In [16]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

`linspace` function takes 3 arguments:
- `start`: The starting value of the range
- `stop`: The ending value of the range
- `num`: The number of values in the range

This might look like the `arange` function, but it's not the same. Linspace generates a range of numbers with `evenly spaced values` between `start` and `stop` with `num` number of values.

Let's say I want 5 numbers between 0 and 5. `Linspace` will return a list of 5 numbers between 0 and 5 with all the numbers evenly spaced.

In [17]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

As you can see we have an array `[1,2,3,4,5]`. You can put any number as arguments and it will generate the array.

> Let's say we want to create an array of 30 numbers from 45 to 100. All the numbers should be equally spaced.

In [18]:
np.linspace(start=45, stop=100, num=30)

array([ 45.        ,  46.89655172,  48.79310345,  50.68965517,
        52.5862069 ,  54.48275862,  56.37931034,  58.27586207,
        60.17241379,  62.06896552,  63.96551724,  65.86206897,
        67.75862069,  69.65517241,  71.55172414,  73.44827586,
        75.34482759,  77.24137931,  79.13793103,  81.03448276,
        82.93103448,  84.82758621,  86.72413793,  88.62068966,
        90.51724138,  92.4137931 ,  94.31034483,  96.20689655,
        98.10344828, 100.        ])

I hope, you understood the `linspace` function. 

Now, before going to other things, , one thing in this linspace section, got my mind. It the `dots` after each number in this example.

In [19]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

We are generating 5 numbers from a uniform distribution between 1 to 5 and we can see that the numbers are `1,2,3,4,5` but still there is the dot after each number(`1.`,`2.`,`3.`,`4.`,`5.`). Why is that?

We should check the type of the return value of `numpy.linspace(1,5,5)`.

In [21]:
arr = np.linspace(1,5,5)
arr.dtype

dtype('float64')

> We can use the `arr.dtype` attribute from any numpy array variable to get the data type of the array.

As you can see even though we have a numpy array of all whole numbers, the data type is still `float64`.

So, by default, `linspace` function returns a `float64` array.

Now let's talk about `indentity` matrix.

If you don't know what an identity matrix is, it's a square matrix with ones on the main diagonal and zeros elsewhere.

> It is also used to represent `1` in matrix.

Simply, `1` can be written as

$$
\begin{bmatrix}
1 & 0 & 0 & \cdots & 0 \\
0 & 1 & 0 & \cdots & 0 \\
0 & 0 & 1 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & 1
\end{bmatrix}
$$

It can be a square matrix of any size. `1x1`, `2x2`, `3x3`, `n x n` etc.

All of this is just a matrix representation of `1`.

And in numpy, we can get an identity matrix of any size by using `np.eye` function.

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

> When you multiply a matrix by a Identity matrix, you get the same matrix back.

# Random

One of the most useful modules in `numpy` is `random`. It provides a number of functions to generate random numbers it different distributions.

> We will visualize what different distributions look like in the visualizations library articles.

This `random` module is not far off from the `random` module in Python's standard library. The main difference is that `numpy` has a number of functions to generate random numbers in different distributions.

So, what about we generate a array of random numbers?

In [23]:
np.random.rand()

0.2637810768348473

> `rand()` mathod will return a random number between 0 and 1.

We can get an array of random numbers between 0 and 1 by using the `rand()` method too.

In [24]:
np.random.rand(3)

array([0.20235773, 0.19999971, 0.4462011 ])

If you want a 2D array, you can just pass the number of rows and columns.

In [27]:
np.random.rand(3,4)

array([[0.75704793, 0.43485018, 0.14997488, 0.48661208],
       [0.55896712, 0.90591318, 0.32762082, 0.48353478],
       [0.96958056, 0.40637603, 0.69959379, 0.33193069]])

We can make as many dimentions we want. Just pass the size of the dimentions and this method will create the array with the given dimentions.

In [28]:
np.random.rand(2,3,2,4)

array([[[[0.08691663, 0.17088443, 0.11837669, 0.85721939],
         [0.13007443, 0.86760089, 0.82462539, 0.38911562]],

        [[0.74100744, 0.50632947, 0.44063465, 0.0729541 ],
         [0.62075949, 0.77061905, 0.35113216, 0.85218243]],

        [[0.10859144, 0.74240741, 0.46840081, 0.93851261],
         [0.10588262, 0.48566231, 0.0246388 , 0.61082481]]],


       [[[0.85177588, 0.39478967, 0.47254821, 0.53919674],
         [0.92340437, 0.26418839, 0.65563583, 0.42199112]],

        [[0.40958923, 0.02075677, 0.10758335, 0.64464445],
         [0.15094235, 0.44701903, 0.84610367, 0.6969326 ]],

        [[0.406591  , 0.22789348, 0.59403528, 0.87939375],
         [0.75349755, 0.78534703, 0.84661362, 0.32354451]]]])

Now, the values generated from the `rand` function is from the `uniform` distribution. We can generate random numbers from `gaussian` distribution or `normal` distribution using the `randn` function.

In [29]:
np.random.randn(3,4)

array([[-0.17239173, -1.42657961, -1.91757699,  0.08522032],
       [ 1.67533517,  0.06761274, -1.8728889 , -0.7556542 ],
       [ 0.85058579,  1.23327789, -0.08622355, -2.33977427]])

This works as same as the `rand` function. But the number generated is from `normal distribution`. That's why you can see negetive numbers as well.

These are all numbers between -1 and 1.

But what if you need interger numbers? You can use `np.random.randint(low, high, size)`

In [30]:
np.random.randint(1, 100, size=5)

array([95, 67, 64, 46, 41])

`randint` method will generate rnaodm integers between min and max values and if you want an array or a matrix or highers dimension you can set the size or dimension size as a tuple.

In [32]:
np.random.randint(20,50, size=(2,3,6))

array([[[41, 32, 37, 48, 29, 45],
        [25, 26, 49, 32, 41, 48],
        [27, 31, 34, 33, 39, 44]],

       [[41, 44, 47, 46, 45, 20],
        [33, 49, 37, 48, 43, 30],
        [26, 45, 31, 35, 26, 34]]])

Pretty easy right? 😃

This module is very useful when you want a dummy data to work with. It's a very simple module that you can use to create a dummy dataset very fast.

Now, I hope you got the gist of what numpy is and how it works. Now time for some useful functions that can help you undersand the `array` better.

## Some Useful Functions

With numpy, it is very easy to create a multidimensional array. But sometime seeing a multidimensional array can be a bit confusing and hard to wrap your head around. But it helps if we can know the shape of a array.

So, let's experiment.

In [33]:
rarr = np.random.randint(1,50,size=(10,5))
rarr

array([[18, 29, 26, 20, 25],
       [34,  7, 49, 34, 42],
       [ 1, 16, 38, 17, 45],
       [42, 47, 34, 40,  1],
       [38, 19,  4, 29, 20],
       [10, 19, 47, 27, 48],
       [ 5, 13, 16, 16, 20],
       [47, 41, 17, 41,  5],
       [16, 26,  9, 42, 37],
       [45, 32, 15,  6, 30]])

Here I created a matrix of size `10x5`, for me it is pretty easy to understand, but if you are a only seeing this array for the first time you might get confused. So, what we can do is, see the shape of the array.

In [34]:
rarr.shape

(10, 5)

`shape` is a numpy array attribute that returns the shape of the array. I created the `10x5` array and with simple command you can also see that it is a 2D matrix that has 10 rows and 5 columns.

Now, what if you want to change the size of the rows or columns? You can do that by using the `reshape` method. Let's see how it works.

In [35]:
rarr.reshape(5,10)

array([[18, 29, 26, 20, 25, 34,  7, 49, 34, 42],
       [ 1, 16, 38, 17, 45, 42, 47, 34, 40,  1],
       [38, 19,  4, 29, 20, 10, 19, 47, 27, 48],
       [ 5, 13, 16, 16, 20, 47, 41, 17, 41,  5],
       [16, 26,  9, 42, 37, 45, 32, 15,  6, 30]])

Here you can see I interchange the rows and columns of a matrix. And it is seamlessly done by numpy.

> reshape() method doesn't reshape the matrix, it just returns a new matrix with the same data but with a different shape. So, to permanently change the shape of a matrix, you can store the reshaped matrix in a new variable or in the same variable.

Now, can we change the whole array into any shape?

In [37]:
rarr.reshape(2,5)

ValueError: cannot reshape array of size 50 into shape (2,5)

And it's showing an error. This error is because we are trying to change the share of the array in a wrong shape. We need to change the shape of the array in a way that it doesn't doesn't change the elements of the array.

The `rarr` array has a shape of `(10, 5)`. So, it has 50 elements. But, we want to change the shape of the array to `(2,5)`. Which means the matrix can have only 10 elements. Which is not possible. So, we should be careful when reshaping the array.

> One clever way to reshape is to multiply the sizes of different dimensions and check if it's equal to the total number of elements in the array. 

So, that means the number of elements should not change so. If I want to reshape the array to `(5,2,5)` then it should work right?

In [38]:
rarr.reshape(5,2,5)

array([[[18, 29, 26, 20, 25],
        [34,  7, 49, 34, 42]],

       [[ 1, 16, 38, 17, 45],
        [42, 47, 34, 40,  1]],

       [[38, 19,  4, 29, 20],
        [10, 19, 47, 27, 48]],

       [[ 5, 13, 16, 16, 20],
        [47, 41, 17, 41,  5]],

       [[16, 26,  9, 42, 37],
        [45, 32, 15,  6, 30]]])

Yes! It works. Because in the end `5x2x5=50` and we are not changing the element size.

With that out of the way, now let's think about some more thing we should be able to do.

Ow! I got one.

How do we find the maximum or the minimum value in a numpy array?

In [39]:
arr = np.random.randint(1,100,size=30)

For finding the maximum value:

In [41]:
arr.max()

np.int64(98)

For finding the minimum value:

In [42]:
arr.min()

np.int64(13)

Noice! But what if I tell you to find the index of the maximum value or the minimum value of a list? `Python` doesn't provide a direct way to do that but `Numpy` does. 

To get the index of the maximum value of a numpy array:

In [43]:
arr.argmax()

np.int64(6)

To find the index of the minimum value:

In [44]:
arr.argmin()

np.int64(4)

And I think that covers the elementary stuff. And we can now go on to the more complecated stuff.