Bois! We are going Deep DEep DEEp DEEEEEP inside `ML`. And we will face some roadblocks. First one is `numpy`.

This is a entry point and the first `boss` fight of this series. Because almost everything after this point is written in `numpy` or uses `numpy` functions. So, understanding and having a good knowledge of `numpy` is very important. So, without further ado, let's defeat `numpy`.

- [LinkedIn](https://www.linkedin.com/in/pro-programmer/)
- [YouTube](http://www.youtube.com/@itvaya)
- [gtihub](https://github.com/RishatTalukder/Machine-Learning-Zero-to-Hero)
- [Gmail](talukderrishat2@gmail.com)
- [discord](https://discord.gg/ZB495XggcF)

# Installation

You need `conda` installed in you system. If you don't have it, you can install it from [here](https://www.anaconda.com/products/distribution).

If you have `conda` installed, Just run the following command in your terminal:

```bash
conda install numpy
```

And 

If you don't have `conda` installed, you can still intall `numpy` on base `python` by running the following command:

```bash
pip install numpy
```

> I heavily recommend you to use `conda` for installing `numpy` because it will install all the dependencies of `numpy` and you will have less errors as our python package ecosystem grows.

# Intro

`Numpy` is faster `python`.

That's it end the article here. If you know `python` you already know 80% of `numpy`. 

Numpy specializes in `numerical computing`, specifically `arrays`.

> If you take python and optimise it so hard that it becomes faster than C++, you can call it `numpy`.

We can do everything we can do in `python` with `numpy` but it's waaaay faster than `python`.

But the main use case of `numpy` is `array/vector/matrix` operations. And that's what we will be doing in this article.

Let's take an array.

In [1]:
arr = [1,2,3,4,5]
arr

[1, 2, 3, 4, 5]

Here you can see a very simple python list. Which is pretty powerful on its own. But with numpy it becomes a superpower.

We can transform any array into a numpy array by using the `array()` function from numpy. We have to import `numpy` first because it's a external library.

In [2]:
import numpy as np

narr = np.array([1,2,3,4,5])
narr

array([1, 2, 3, 4, 5])

> In python you can rename a library when imported by using the `as` keyword. For example, if you import `numpy` as `np` you can use it as `np.array()` instead of `numpy.array()`.

Here you can see that by using the `np.array()` we are transforming our simple python list into a numpy array.

We can do the same thing with a 2D list as well.

In [3]:
arr_2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
narr_2D = np.array(arr_2D)
narr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

A numpy array gives us a lot of methods and attributes to work with the data. 

> A vector is a one-dimensional array which is a traditional array of numbers.
> A matrix is a two-dimensional array.

# Numpy Methods

There are a lot of methods that we can use to make and work with numpy arrays. 

First we can talk about the `arange` method. 

## Numpy Arange

This is equivalent to the python `range` function. Works exactly the same way.

In the range function, we can specify the start, stop, and step values.

And it generates a sequence of numbers from start to stop by step.

This is exactly what the `arange` method does. It also takes the start, stop, and step values and generates a sequence of numbers from start to stop by step.

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Just like for the range function, the start value in inclusive and the end value is exclusive. It's the same for `arange`.
> By default the starting index is set to 0 and the steps are 1.

In [5]:
np.arange(35, 45, 2)

array([35, 37, 39, 41, 43])

# Some Quick Numpy Array generators

If you want a array of all zeros, you can use the `zeros` function:

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

This will generate a numpy array of 5 zeros. We can also make a `matrix(2D)` array by specifying the number of `rows and columns` in a `tuple`.

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

And it'll generate a `3x4` matrix. The cool part is we can make 3D or more than 4D array of all zeros with this.

In [8]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

Numpy has another function that can generate arrays filled with only `one's`. This function is called `ones`. 

In [10]:
print('Array of 4 ones')
a = np.ones(4)
print(a)

print('2D array of all ones')
b = np.ones((2,2))
print(b)

print('3D array of all ones')
c = np.ones((2,2,2))
print(c)

Array of 4 ones
[1. 1. 1. 1.]
2D array of all ones
[[1. 1.]
 [1. 1.]]
3D array of all ones
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


This method works exactly same the `zeros` method, but it generates array of any dimentions with all elements as `Ones`.

Now, another very useful method I want to talk about is `linspace` method. This method is used to generate array with evenly spaced elements.

Let me break it down with an example.

In [11]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

`linspace` function takes 3 arguments:
- `start`: The starting value of the range
- `stop`: The ending value of the range
- `num`: The number of values in the range

This might look like the `arange` function, but it's not the same. Linspace generates a range of numbers with `evenly spaced values` between `start` and `stop` with `num` number of values.

Let's say I want 5 numbers between 0 and 5. `Linspace` will return a list of 5 numbers between 0 and 5 with all the numbers evenly spaced.

In [12]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

As you can see we have an array `[1,2,3,4,5]`. You can put any number as arguments and it will generate the array.

> Let's say we want to create an array of 30 numbers from 45 to 100. All the numbers should be equally spaced.

In [13]:
np.linspace(start=45, stop=100, num=30)

array([ 45.        ,  46.89655172,  48.79310345,  50.68965517,
        52.5862069 ,  54.48275862,  56.37931034,  58.27586207,
        60.17241379,  62.06896552,  63.96551724,  65.86206897,
        67.75862069,  69.65517241,  71.55172414,  73.44827586,
        75.34482759,  77.24137931,  79.13793103,  81.03448276,
        82.93103448,  84.82758621,  86.72413793,  88.62068966,
        90.51724138,  92.4137931 ,  94.31034483,  96.20689655,
        98.10344828, 100.        ])

I hope, you understood the `linspace` function. 

Now, before going to other things, , one thing in this linspace section, got my mind. It the `dots` after each number in this example.

In [14]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

We are generating 5 numbers from a uniform distribution between 1 to 5 and we can see that the numbers are `1,2,3,4,5` but still there is the dot after each number(`1.`,`2.`,`3.`,`4.`,`5.`). Why is that?

We should check the type of the return value of `numpy.linspace(1,5,5)`.

In [15]:
arr = np.linspace(1,5,5)
arr.dtype

dtype('float64')

> We can use the `arr.dtype` attribute from any numpy array variable to get the data type of the array.

As you can see even though we have a numpy array of all whole numbers, the data type is still `float64`.

So, by default, `linspace` function returns a `float64` array.

Now let's talk about `indentity` matrix.

If you don't know what an identity matrix is, it's a square matrix with ones on the main diagonal and zeros elsewhere.

> It is also used to represent `1` in matrix.

Simply, `1` can be written as

$$
\begin{bmatrix}
1 & 0 & 0 & \cdots & 0 \\
0 & 1 & 0 & \cdots & 0 \\
0 & 0 & 1 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & 1
\end{bmatrix}
$$

It can be a square matrix of any size. `1x1`, `2x2`, `3x3`, `n x n` etc.

All of this is just a matrix representation of `1`.

And in numpy, we can get an identity matrix of any size by using `np.eye` function.

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

> When you multiply a matrix by a Identity matrix, you get the same matrix back.

# Random

One of the most useful modules in `numpy` is `random`. It provides a number of functions to generate random numbers it different distributions.

> We will visualize what different distributions look like in the visualizations library articles.

This `random` module is not far off from the `random` module in Python's standard library. The main difference is that `numpy` has a number of functions to generate random numbers in different distributions.

So, what about we generate a array of random numbers?

In [17]:
np.random.rand()

0.07827277408870692

> `rand()` mathod will return a random number between 0 and 1.

We can get an array of random numbers between 0 and 1 by using the `rand()` method too.

In [18]:
np.random.rand(3)

array([0.242575  , 0.8606522 , 0.31061968])

If you want a 2D array, you can just pass the number of rows and columns.

In [19]:
np.random.rand(3,4)

array([[0.24409248, 0.389826  , 0.69092572, 0.80462688],
       [0.96486607, 0.81463593, 0.90473991, 0.99803197],
       [0.25361529, 0.32909625, 0.7791001 , 0.65627824]])

We can make as many dimentions we want. Just pass the size of the dimentions and this method will create the array with the given dimentions.

In [20]:
np.random.rand(2,3,2,4)

array([[[[0.38291862, 0.1718719 , 0.01005473, 0.22531748],
         [0.69280543, 0.30722777, 0.20322226, 0.21503826]],

        [[0.94697016, 0.9756886 , 0.73332531, 0.91217825],
         [0.43012593, 0.51549038, 0.29700247, 0.96424557]],

        [[0.13375404, 0.6732027 , 0.03343003, 0.37060941],
         [0.98302811, 0.51951977, 0.45867878, 0.49231021]]],


       [[[0.84962164, 0.87562243, 0.71487625, 0.86458622],
         [0.40254173, 0.83530846, 0.30676251, 0.13880142]],

        [[0.11531409, 0.43952691, 0.26100778, 0.73855068],
         [0.0661455 , 0.39913933, 0.45509843, 0.03158511]],

        [[0.49576648, 0.60779303, 0.78371644, 0.13846923],
         [0.57722093, 0.1880645 , 0.66056368, 0.46715857]]]])

Now, the values generated from the `rand` function is from the `uniform` distribution. We can generate random numbers from `gaussian` distribution or `normal` distribution using the `randn` function.

In [21]:
np.random.randn(3,4)

array([[-0.31466131,  0.19646857,  0.07710423,  0.57714849],
       [-0.50617123, -0.59589996,  0.08223177, -0.30799569],
       [-0.00741355, -1.59943092,  0.17594932,  1.09847189]])

This works as same as the `rand` function. But the number generated is from `normal distribution`. That's why you can see negetive numbers as well.

These are all numbers between -1 and 1.

But what if you need interger numbers? You can use `np.random.randint(low, high, size)`

In [22]:
np.random.randint(1, 100, size=5)

array([58, 52, 31,  6, 22])

`randint` method will generate rnaodm integers between min and max values and if you want an array or a matrix or highers dimension you can set the size or dimension size as a tuple.

In [23]:
np.random.randint(20,50, size=(2,3,6))

array([[[46, 26, 32, 32, 30, 33],
        [27, 33, 41, 45, 42, 31],
        [33, 21, 27, 49, 24, 27]],

       [[49, 34, 24, 49, 45, 26],
        [43, 42, 24, 32, 36, 33],
        [48, 30, 43, 26, 37, 34]]])

Pretty easy right? 😃

This module is very useful when you want a dummy data to work with. It's a very simple module that you can use to create a dummy dataset very fast.

Now, I hope you got the gist of what numpy is and how it works. Now time for some useful functions that can help you undersand the `array` better.

## Some Useful Functions

With numpy, it is very easy to create a multidimensional array. But sometime seeing a multidimensional array can be a bit confusing and hard to wrap your head around. But it helps if we can know the shape of a array.

So, let's experiment.

In [24]:
rarr = np.random.randint(1,50,size=(10,5))
rarr

array([[19, 33, 46, 12,  2],
       [11, 39, 30, 24, 25],
       [ 8, 48, 35, 29, 20],
       [29, 12, 22, 44, 44],
       [29,  4, 10, 49,  2],
       [46, 18,  8, 15,  6],
       [ 3,  3, 35, 13,  1],
       [13, 10, 35, 18, 16],
       [ 1, 11, 42, 45, 30],
       [39, 25, 31, 14, 19]])

Here I created a matrix of size `10x5`, for me it is pretty easy to understand, but if you are a only seeing this array for the first time you might get confused. So, what we can do is, see the shape of the array.

In [25]:
rarr.shape

(10, 5)

`shape` is a numpy array attribute that returns the shape of the array. I created the `10x5` array and with simple command you can also see that it is a 2D matrix that has 10 rows and 5 columns.

Now, what if you want to change the size of the rows or columns? You can do that by using the `reshape` method. Let's see how it works.

In [26]:
rarr.reshape(5,10)

array([[19, 33, 46, 12,  2, 11, 39, 30, 24, 25],
       [ 8, 48, 35, 29, 20, 29, 12, 22, 44, 44],
       [29,  4, 10, 49,  2, 46, 18,  8, 15,  6],
       [ 3,  3, 35, 13,  1, 13, 10, 35, 18, 16],
       [ 1, 11, 42, 45, 30, 39, 25, 31, 14, 19]])

Here you can see I interchange the rows and columns of a matrix. And it is seamlessly done by numpy.

> reshape() method doesn't reshape the matrix, it just returns a new matrix with the same data but with a different shape. So, to permanently change the shape of a matrix, you can store the reshaped matrix in a new variable or in the same variable.

Now, can we change the whole array into any shape?

In [27]:
rarr.reshape(2,5)

ValueError: cannot reshape array of size 50 into shape (2,5)

And it's showing an error. This error is because we are trying to change the share of the array in a wrong shape. We need to change the shape of the array in a way that it doesn't doesn't change the elements of the array.

The `rarr` array has a shape of `(10, 5)`. So, it has 50 elements. But, we want to change the shape of the array to `(2,5)`. Which means the matrix can have only 10 elements. Which is not possible. So, we should be careful when reshaping the array.

> One clever way to reshape is to multiply the sizes of different dimensions and check if it's equal to the total number of elements in the array. 

So, that means the number of elements should not change so. If I want to reshape the array to `(5,2,5)` then it should work right?

In [28]:
rarr.reshape(5,2,5)

array([[[19, 33, 46, 12,  2],
        [11, 39, 30, 24, 25]],

       [[ 8, 48, 35, 29, 20],
        [29, 12, 22, 44, 44]],

       [[29,  4, 10, 49,  2],
        [46, 18,  8, 15,  6]],

       [[ 3,  3, 35, 13,  1],
        [13, 10, 35, 18, 16]],

       [[ 1, 11, 42, 45, 30],
        [39, 25, 31, 14, 19]]])

Yes! It works. Because in the end `5x2x5=50` and we are not changing the element size.

With that out of the way, now let's think about some more thing we should be able to do.

Ow! I got one.

How do we find the maximum or the minimum value in a numpy array?

In [29]:
arr = np.random.randint(1,100,size=30)

For finding the maximum value:

In [30]:
arr.max()

np.int64(97)

For finding the minimum value:

In [31]:
arr.min()

np.int64(14)

Noice! But what if I tell you to find the index of the maximum value or the minimum value of a list? `Python` doesn't provide a direct way to do that but `Numpy` does. 

To get the index of the maximum value of a numpy array:

In [32]:
arr.argmax()

np.int64(3)

To find the index of the minimum value:

In [33]:
arr.argmin()

np.int64(2)

And I think that covers the elementary stuff. And we can now go on to the more complecated stuff.

# Indexing

One of the best things about numpy is that it allows you high level indexing. So you can do things like,
- `Selecting`.
- `Slicing`.
- `n-D matrix slicing`.
- `Conditional indexing`.

And many more.

Also, you can do indexing just like you would in python.

In [34]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[5]

np.int64(5)

As you can see selecting any index is the same as we do in python lists. 

And indexing like [-1] is also present in numpy arrays. 

In [36]:
arr[-1]

np.int64(10)

It's all the same as the base python. But numpy excels in handling slicing. For a normal vector, it's the same as python. 

We can use colon `[:]` to select all the elements of an array.

> `[start:end:step]`
> Start is set to 0 by default.
> End is set to the length of the array by default.
> Step is set to 1 by default.

So, Let's say I want values from index 0 to 4, I can do this:

In [37]:
arr[0:5]

array([0, 1, 2, 3, 4])

The end value is exclusive, so `5th` index is excluded and we get a list of values from `0` to `4`.

> Just remember to put (index you want + 1). If you want from `0` to `4` then you have to put `[0:5]` or if you want from `3` to `7` then you have to put `[3:8]`.

As the default start index is set to `0` if you want a slice from beginning to any index you can keep the start index empty and just put the end index.

In [38]:
arr[:3]

array([0, 1, 2])

It's the same as

In [39]:
arr[0:3:1] # start from 0, step by 1, stop at 3

array([0, 1, 2])

If you want a slice from a specific index to the end of the array, you can keep the end index empty too. Because the end index is set to the length of the array by default.

In [40]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

You can also experiment with the step size too

In [41]:
arr[:8] # first 8 elements

array([0, 1, 2, 3, 4, 5, 6, 7])

In [42]:
arr[:8:2] # start from index 0 and take every 2nd element to the 7th element

array([0, 2, 4, 6])

Looks good. But one thing that might just through you off, is when you want to store a slice in a different variable.

In [43]:
arr_2 = arr[1:7]
arr_2

array([1, 2, 3, 4, 5, 6])

Easy and looks just like python right?

Now, we can do indexing in this new sliced array.

In [44]:
arr_2[2:]

array([3, 4, 5, 6])

Looks great!

Nothing out of the ordinary here. Let's try to change a value in the array.

In [45]:
arr_2[2] = 99
arr_2

array([ 1,  2, 99,  4,  5,  6])

We can change values of a numpy array exactly we do in a python list.

BUUUUUUT

If I look at the main array, Some interesting will happen.

In [46]:
arr

array([ 0,  1,  2, 99,  4,  5,  6,  7,  8,  9, 10])

WHAT! 

The Main array changed! Why?! HOW?!

I changed the value of the sliced array but why would the main array change?

This is because the numpy doesn't copy the array when slicing. It just broadcasts the sliced array to any other variable.

So, when we `slice` the array, it is `not` taking any `new space` in the memory. It is just that the sliced that is `directly broadcasted`. And if we `store` that slice in a `new variable`, it'll look like and feel like a new array but still it is a `part` of the main array which we are just using as a new variable.

So, if we `change` an array that is `sliced` from another numpy array, it will change the main array.

Let's make a new array named `main_arr`:

In [47]:
main_arr = np.arange(20)
main_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Now get a slice of the array,

In [48]:
sliced_arr = main_arr[3:13]
sliced_arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Change the whole slice to 12

In [49]:
sliced_arr[:] = 12 # changing the values of the whole array
sliced_arr

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

Now, let's take a look at the main array

In [50]:
main_arr

array([ 0,  1,  2, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 14, 15, 16,
       17, 18, 19])

And you can see the that the sliced part of the main array has also changed to 12.

> That's why be careful when you are slicing an array. Because you might unintentionally change the original array.

And if you want a copy of the slice, you can use the copy() method.

This method will return a copy of the slice instead of braodcasting the slice from the original array.

In [51]:
main_arr = np.arange(10)
print(f"main array is {main_arr}")

copied_slice = main_arr[4:9].copy()
print(f"copied slice is {copied_slice}")

#changing the whole array to 99
copied_slice[:] = 99
print(f'changed the array to {copied_slice}')
print(f'main array is {main_arr}')

main array is [0 1 2 3 4 5 6 7 8 9]
copied slice is [4 5 6 7 8]
changed the array to [99 99 99 99 99]
main array is [0 1 2 3 4 5 6 7 8 9]


This way your original array will be unaffected.

Now, for the fun part.

# Matrix Indexing

`Numpy` specializes in matrix handling. 

In [52]:
matrix = np.array([[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400], [1000, 2000, 3000, 4000]])
matrix

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

In numpy, there's two ways you can index a matrix:

**The python way(double square brackets)**

In [53]:
matrix[0][1]

np.int64(2)

Or,

**The Numpy way (single bracket with comma)**

In [54]:
matrix[0,1]

np.int64(2)

There are both equivalent ways to get elements from a matrix. I would prefer to use the second way, because we are using `numpy` and we should stick to it's syntax to avoid confusions.

Now, let's talk about matrix slicing. The Broadcasting from the original array is still valid. But we get some very useful features for matrix slicing in `numpy`.

Normally if we have a 2D list in python. If we want a cirtain part of that list we have to do it logically.

For example, let's say we have a list like this:

In [55]:
matrix_python = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_python

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

I want the `[[5,6], [8,9]]` slice. 

To get that first we need to slice by rows.

In [56]:
slice = matrix_python[1:]
slice

[[4, 5, 6], [7, 8, 9]]

And now, the issue arrives that we cannot slice by columns in python. So, we need to use a for loop to get the rows in the slice and then get the slice of each row and add them to a new array.

> I know I wrote some shiz you guys didn't understand, me too.

In [57]:
slice = [arr[1:] for arr in slice]
slice

[[5, 6], [8, 9]]

And we have the slice we need. This way too much work. Numpy has a great way to do this.

We have this matrix. 

In [58]:
matrix

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

And I want

$$
\begin{bmatrix}
    20 & 30 \\
    200 & 300 \\
\end{bmatrix}
$$

We can do this simply slicing the array because numpy has column slicing too. 

In [59]:
matrix_slice = matrix[1:3, 1:3]
matrix_slice

array([[ 20,  30],
       [200, 300]])

> We use the comma separated way to slice in numpy for matrices.

If we only want to slice by row. 

We can do that normal way.

In [60]:
matrix[1:]

array([[  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

The best part is if you want `slice by column`, you can use a `comma` to separate the `row` and `column` index.

In [61]:
matrix[:,1:3]

array([[   2,    3],
       [  20,   30],
       [ 200,  300],
       [2000, 3000]])

Here I'm slicing only the column from 1 to 2.

> The end value will be excluded.

So, by `[:, 1:3]`, I saying give me all the rows but the columns from 1 to 2.

> You cannot do direct column slicing like `df[, 1:3]`. It'll show an error.

This can be a tough concept to get the hang of. So, I'll give you a task.

> Make a random array of size 20. Reshape it into a 4x5 matrix. Then, trying indexing the that matrix and then slicing different parts of it.

Try it yourself and remember the end value is excluded.

> I was traumatized by this when I was learning.

There's more type of selections you can do.

# Conditional Selection

Row and Column indexing is one those numpy concepts that is very important to understand but the use-cases are limited. 

`COnditional selection` on the other hand, is a very a very powerful concept and it's use is very frequent in data analysis.

Because it let's you select the data based on conditions.

Let's see an example.

In [62]:
arr = np.random.randint(1,101, size=16)
arr

array([77, 84, 23, 61, 99, 33, 16, 83, 86, 66, 82, 30, 27, 93, 15, 39])

Here, I have a completely random array of numbers. And I don't know what's inside this array. Now, for some reason, I need to an array of all the numbers that are greater than 25. 

Now, if you are somewhat experienced in programming, you might be thinking that we can use a for loop to do this. But, numpy has it's own way.

First let's see what happens if we directly compare the array with a number.

In [63]:
arr > 25

array([ True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True])

Owh! that's shocking instead of returning a single boolean value, when we compare with a numpy array it returns a `boolean array` of the `same` size.

Now what are these boolean values? They represent if the corresponding element of the array meets the condition or not.

As we can see, first value of that array is `True`, that means the first element should be `greater` than `25`.

Let's have a look at the first element of the array.

In [64]:
arr[0]

np.int64(77)

And yes! It's `77` it is most definitely greater than `25`.

Now, the fun part is we can use this boolean array to get a subset of all the values that are greater than `25`. 

In [65]:
boolean_arr = arr > 25
boolean_arr

array([ True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True])

In [66]:
arr[boolean_arr]

array([77, 84, 61, 99, 33, 83, 86, 66, 82, 30, 27, 93, 39])

And look at that, we got a list of all the numbers that are greater than 25.

This is called `conditional indexing/selection`.

We can directly put the condition inside brackets to get the list of numbers that are greater than 25.

In [ ]:
arr[arr > 25]

> I know it's kinda weird to see the variable named inside the brackets, but it's just to tell which elements of the array are satisfying the condition.

all the elements that has a corresponding value of `True` is then returned as a new numpy array.

And when I say `new`, I mean completely new array.

> Check if the array you are getting from conditional selection can change the original array by changing the value of a single element.

We can use every conditional operators and it'll work the same. So, no need of any for loops and no need of a empty array to store the result.

> Remember, the more you experiment with the numpy, the more you'll understand it better.