Bois! We are going Deep DEep DEEp DEEEEEP inside `ML`. And we will face some roadblocks. First one is `numpy`.

This is a entry point and the first `boss` fight of this series. Because almost everything after this point is written in `numpy` or uses `numpy` functions. So, understanding and having a good knowledge of `numpy` is very important. So, without further ado, let's defeat `numpy`.

- [LinkedIn](https://www.linkedin.com/in/pro-programmer/)
- [YouTube](http://www.youtube.com/@itvaya)
- [gtihub](https://github.com/RishatTalukder/Machine-Learning-Zero-to-Hero)
- [Gmail](talukderrishat2@gmail.com)
- [discord](https://discord.gg/ZB495XggcF)

# Installation

You need `conda` installed in you system. If you don't have it, you can install it from [here](https://www.anaconda.com/products/distribution).

If you have `conda` installed, Just run the following command in your terminal:

```bash
conda install numpy
```

And 

If you don't have `conda` installed, you can still intall `numpy` on base `python` by running the following command:

```bash
pip install numpy
```

> I heavily recommend you to use `conda` for installing `numpy` because it will install all the dependencies of `numpy` and you will have less errors as our python package ecosystem grows.

# Intro

`Numpy` is faster `python`.

That's it end the article here. If you know `python` you already know 80% of `numpy`. 

Numpy specializes in `numerical computing`, specifically `arrays`.

> If you take python and optimise it so hard that it becomes faster than C++, you can call it `numpy`.

We can do everything we can do in `python` with `numpy` but it's waaaay faster than `python`.

But the main use case of `numpy` is `array/vector/matrix` operations. And that's what we will be doing in this article.

Let's take an array.

In [2]:
arr = [1,2,3,4,5]
arr

[1, 2, 3, 4, 5]

Here you can see a very simple python list. Which is pretty powerful on its own. But with numpy it becomes a superpower.

We can transform any array into a numpy array by using the `array()` function from numpy. We have to import `numpy` first because it's a external library.

In [3]:
import numpy as np

narr = np.array([1,2,3,4,5])
narr

array([1, 2, 3, 4, 5])

> In python you can rename a library when imported by using the `as` keyword. For example, if you import `numpy` as `np` you can use it as `np.array()` instead of `numpy.array()`.

Here you can see that by using the `np.array()` we are transforming our simple python list into a numpy array.

We can do the same thing with a 2D list as well.

In [4]:
arr_2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
narr_2D = np.array(arr_2D)
narr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

A numpy array gives us a lot of methods and attributes to work with the data. 

> A vector is a one-dimensional array which is a traditional array of numbers.
> A matrix is a two-dimensional array.

# Numpy Methods

There are a lot of methods that we can use to make and work with numpy arrays. 

First we can talk about the `arange` method. 

## Numpy Arange

This is equivalent to the python `range` function. Works exactly the same way.

In the range function, we can specify the start, stop, and step values.

And it generates a sequence of numbers from start to stop by step.

This is exactly what the `arange` method does. It also takes the start, stop, and step values and generates a sequence of numbers from start to stop by step.

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Just like for the range function, the start value in inclusive and the end value is exclusive. It's the same for `arange`.
> By default the starting index is set to 0 and the steps are 1.

In [10]:
np.arange(35, 45, 2)

array([35, 37, 39, 41, 43])

# Some Quick Numpy Array generators

If you want a array of all zeros, you can use the `zeros` function:

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

This will generate a numpy array of 5 zeros. We can also make a `matrix(2D)` array by specifying the number of `rows and columns` in a `tuple`.

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

And it'll generate a `3x4` matrix. The cool part is we can make 3D or more than 4D array of all zeros with this.

In [15]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [16]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

Numpy has another function that can generate arrays filled with only `one's`. This function is called `ones`. 

In [17]:
print('Array of 4 ones')
a = np.ones(4)
print(a)

print('2D array of all ones')
b = np.ones((2,2))
print(b)

print('3D array of all ones')
c = np.ones((2,2,2))
print(c)

Array of 4 ones
[1. 1. 1. 1.]
2D array of all ones
[[1. 1.]
 [1. 1.]]
3D array of all ones
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
